### PR TITLE
[admin] Added menu items #37

### LINKED ISSUE #37: [admin] Add menu items
Blocked by (requires solving first): https://github.com/openwisp/openwisp-utils/issues/106.

Add menu items (openwisp-utils menu) for Subnet and IpAddress models.

References:

- [main navigation menu](https://github.com/openwisp/openwisp-utils#main-navigation-menu)
- https://github.com/openwisp/openwisp-users/blob/master/openwisp_users/apps.py

### PR DESCRIPTION
**Pull request by codesankalp**
Added menu items (openwisp-utils menu) for Subnet and IpAdress models.

This is WIP PR which requires the new version release of openwisp-utils.

Fixes #37

### CODE REVIEW

**Review by nemesisdesign — CHANGES_REQUESTED** [review]
Now you can update openwisp-utils in requirements.txt and requirements-test.txt to `0.7.0` and the build should be fixed.

**Comment by codesankalp** [comment]
`error: openwisp-utils 0.7 is installed but openwisp-utils[rest]~=0.6.0 is required by {'openwisp-users'}`

Updating openwisp-users is required for fixing the build.

Waiting for this https://github.com/openwisp/openwisp-users/pull/189 to be merged.

**Review by nemesisdesign — CHANGES_REQUESTED** [review]
@codesankalp, looks good, could you add a simple admin test that check for the presence of the two menu links please?

Take a look at these tests if you're not familiar with admin tests: https://github.com/openwisp/openwisp-ipam/blob/master/openwisp_ipam/tests/test_admin.py.

**Review by nemesisdesign — APPROVED** [review]
Good work! Thanks :+1:

**Pull request merged**
