### PR TITLE
Added DjangoModelPermissons #59

### PR DESCRIPTION
**Pull request by hasanmdarif**
I have added a permissions.py file in sample_ipam. In this permission.py file, I have added code for DjangoModelPermissions.

### CODE REVIEW

**Review by atb00ker — COMMENTED** [review]
Can you please add some information about why is this change required?

**Comment by hasanmdarif** [comment]
> Can you please add some information about why is this change required?

it restricts POST, PUT and DELETE access but allows VIEW access.

**Review by nemesisdesign — COMMENTED** [review]
@hasanmdarif this PR does not do much.

You aren't expect us to tell you exactly what to do, are you? We are busy. We have work to do, deadlines. If you want to contribute that's great, but your skill level should be sufficient to understand the problem at hand and send patches that at least solve it, then we can suggest you improvements, but this PR does nothing and I can't spend hours explain you what to do and I won't do it.

**Comment by hasanmdarif** [comment]
> @hasanmdarif this PR does not do much.
> 
> You aren't expect us to tell you exactly what to do, are you? We are busy. We have work to do, deadlines. If you want to contribute that's great, but your skill level should be sufficient to understand the problem at hand and send patches that at least solve it, then we can suggest you improvements, but this PR does nothing and I can't spend hours explain you what to do and I won't do it.

I can understand, I'll try to spend more time on your repos. Thanku for enlightening my faults.

**Pull request closed without merging**
