### PR TITLE
[migration] Created default permissions for the default groups #55

### LINKED ISSUE #55: [IPAM/change] Add default permissions to default groups
Create a data migration to create the default permissions for the default group: Administrator and Operator.

Administrator should be granted all permissions on `Subnet` and `IpAddress`.
Operator should have only view permission on `Subnet` while it should be granted all permissions on `IpAddress`.

For reference, see how it's done in other modules (so a certain degree of consistency can also be maintained):

- [openwisp-controller](https://github.com/openwisp/openwisp-controller/blob/master/openwisp_controller/config/migrations/0015_default_groups_permissions.py)
- [openwisp-radius](https://github.com/openwisp/openwisp-radius/blob/master/openwisp_radius/migrations/0004_default_permissions.py)
-  [openwisp-network-topology](https://github.com/openwisp/openwisp-network-topology/blob/master/openwisp_network_topology/migrations/0005_default_operator_permission.py)

### PR DESCRIPTION
**Pull request by ManishShah120**
Created a data migration to grant permissions to default groups.

fixes #55

### CODE REVIEW

**Comment by ManishShah120** [comment]
@nemesisdesign , @atb00ker

**Review by nemesisdesign — CHANGES_REQUESTED** [review]
@ManishShah120 can you please add a simple test that checks for the presence of the new permissions? 
Please keep in mind automated tests are the only way to ensure the functionality we add won't be broken by other developers inadvertently, if we don't write tests, the functionality can be broken by your future self or other developers.

**Comment by ManishShah120** [comment]
@nemesisdesign , @atb00ker  Please have a look I have added the tests for checking the presence of the new permissions of the admin and operator group. But I don't know why the Travis CI is failing?

**Comment by ManishShah120** [comment]
I am closing this PR and opening a new one, since the last commit in this PR was not passing the Travis CI tests.

**Pull request closed without merging**
